// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"documentation/index.mdx": () => import("../content/docs/documentation/index.mdx?collection=docs"), "documentation/quickstart.mdx": () => import("../content/docs/documentation/quickstart.mdx?collection=docs"), "examples/sui-flows.mdx": () => import("../content/docs/examples/sui-flows.mdx?collection=docs"), "examples/walrus-sites.mdx": () => import("../content/docs/examples/walrus-sites.mdx?collection=docs"), "guides/architecture.mdx": () => import("../content/docs/guides/architecture.mdx?collection=docs"), "guides/components.mdx": () => import("../content/docs/guides/components.mdx?collection=docs"), "guides/deploy.mdx": () => import("../content/docs/guides/deploy.mdx?collection=docs"), "guides/installation.mdx": () => import("../content/docs/guides/installation.mdx?collection=docs"), "guides/llm-setup.mdx": () => import("../content/docs/guides/llm-setup.mdx?collection=docs"), "guides/safety.mdx": () => import("../content/docs/guides/safety.mdx?collection=docs"), "guides/troubleshooting.mdx": () => import("../content/docs/guides/troubleshooting.mdx?collection=docs"), "guides/validate.mdx": () => import("../content/docs/guides/validate.mdx?collection=docs"), "guides/writing-content.mdx": () => import("../content/docs/guides/writing-content.mdx?collection=docs"), "reference/cli.mdx": () => import("../content/docs/reference/cli.mdx?collection=docs"), "reference/env-vars.mdx": () => import("../content/docs/reference/env-vars.mdx?collection=docs"), "documentation/examples/sui-flows.mdx": () => import("../content/docs/documentation/examples/sui-flows.mdx?collection=docs"), "documentation/examples/walrus-sites.mdx": () => import("../content/docs/documentation/examples/walrus-sites.mdx?collection=docs"), "documentation/guides/architecture.mdx": () => import("../content/docs/documentation/guides/architecture.mdx?collection=docs"), "documentation/guides/installation.mdx": () => import("../content/docs/documentation/guides/installation.mdx?collection=docs"), "documentation/guides/llm-setup.mdx": () => import("../content/docs/documentation/guides/llm-setup.mdx?collection=docs"), "documentation/guides/safety.mdx": () => import("../content/docs/documentation/guides/safety.mdx?collection=docs"), "documentation/guides/troubleshooting.mdx": () => import("../content/docs/documentation/guides/troubleshooting.mdx?collection=docs"), "documentation/reference/cli.mdx": () => import("../content/docs/documentation/reference/cli.mdx?collection=docs"), "documentation/reference/env-vars.mdx": () => import("../content/docs/documentation/reference/env-vars.mdx?collection=docs"), }),
};
export default browserCollections;