import type { BaseLayoutProps } from 'fumadocs-ui/layouts/shared';
import Image from 'next/image';

// This file is GENERATED by the cmdocs pipeline from docs.json.
// Do not edit manually — your changes will be overwritten.

export function baseOptions(): BaseLayoutProps {
  return {
    nav: {
      title: (<><Image src="/logo/light-logo-only.svg" alt="Commando" width={24} height={24} className="size-6 dark:hidden" /><Image src="/logo/dark-logo-only.svg" alt="Commando" width={24} height={24} className="size-6 hidden dark:block" />Commando</>),
    },
      githubUrl: 'https://github.com/bernieweb3/commando',
  };
}

export const sidebarOptions = {
  collapsible: true,
  defaultOpenLevel: 0,
};

export const showTabs = true;

export const tabMode = 'auto' as const;

export const explicitTabs: Array<{
  title: string;
  description?: string;
  icon?: string;
  url: string;
  urls?: string[];
  unlisted?: boolean;
}> | null = [
  {
    title: 'Documentation',
    description: 'Learn how to use Commando',
    icon: 'BookOpen',
    url: '/documentation',
    urls: ['/documentation', '/documentation/quickstart', '/documentation/guides/installation', '/documentation/guides/architecture', '/documentation/guides/llm-setup', '/documentation/guides/safety', '/documentation/guides/troubleshooting', '/documentation/examples/sui-flows', '/documentation/examples/walrus-sites', '/documentation/reference/cli', '/documentation/reference/env-vars'],
  },
];

export const pageDisplayOptions = {
  toc: { enabled: true, style: 'normal' as const },
  breadcrumb: true,
  lastUpdated: true,
};

export const rootRedirect: string | null = '/documentation';
