// GENERATED by cmdocs pipeline from docs.json — do not edit.

export const seoConfig = {
  siteName: 'Commando Docs',
  siteDescription: 'Documentation for Commando v0.2.4-beta — natural-language CLI agent for the Sui ecosystem (Windows, Linux, macOS).',
  baseUrl: '',
  titleTemplate: '%s — Commando (cmdo)',
  canonical: true,
  robots: 'index, follow',
  ogImage: '',
} as const;
